/* eslint-disable @next/next/no-before-interactive-script-outside-document */
import Script from "next/script";
import "../../public/antd.min.css";
import "./globals.css";
import NavigationBar from "@/components/NavigationBar";
import QueryProvider from "@/libs/providers/QueryProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <main className="py-12 max-w-screen-sm mx-auto">
          <QueryProvider>{children}</QueryProvider>
          <NavigationBar />
        </main>
        <Script
          src={`https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=${process.env.NEXT_PUBLIC_MAP_CLIENT_ID}`}
        />
      </body>
    </html>
  );
}
